In [2]:
import numpy as np

my_arr = np.array(1_000_000)
my_list = list(range(1_000_000))


In [3]:
%timeit my_arr2 = my_arr * 2

421 ns ± 2.16 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [4]:
%timeit my_list2 = [x * 2 for x in my_list]

34.3 ms ± 448 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


# ndarry:多维数组对象

In [10]:
data = np.array([[1.5, -0.1, 3],[0, -3, 6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [11]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [12]:
data+data


array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [14]:
data.shape

(2, 3)

In [15]:
data.dtype

dtype('float64')

## 创建ndarray

In [16]:
data1 = [6,7,8,9,1]
arr1 = np.array(data1)
arr1

array([6, 7, 8, 9, 1])

In [17]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
arr2.ndim

2

In [19]:
arr2.shape

(2, 4)

In [20]:
arr2.dtype

dtype('int32')

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [167]:
np.empty((9,9,9),dtype='int32')

array([[[ -918939024,         515,  -918928912,         515,
          -918928800,         515,  -918938944,         515,
          -918928688],
        [        515,  -918928576,         515,  -918938864,
                 515,  -918928464,         515,  -918928352,
                 515],
        [ -918938784,         515,  -918928240,         515,
          -918928128,         515,  -918938704,         515,
         -1060208592],
        [        515,  -918928016,         515,  -918927904,
                 515,  -918938624,         515,  -918927792,
                 515],
        [ -918927680,         515,  -918938544,         515,
          -918927568,         515,  -918927456,         515,
          -918938464],
        [        515,  -918927344,         515,  -918927232,
                 515,  -918938384,         515,  -918927120,
                 515],
        [ -918927008,         515,  -918938304,         515,
          -918926896,         515,  -918926784,         515,
        

In [168]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [173]:
np.full((3,3),100)

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

## ndarray的数据类型

In [174]:
arr1 = np.array([1,2,3],dtype=np.float32)

arr1.dtype

dtype('float32')

In [175]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [176]:
float_arr = arr.astype(np.float64)
float_arr

array([1., 2., 3., 4., 5.])

In [177]:
float_arr.dtype

dtype('float64')

In [178]:
numeric_str = np.array(["1.23","-9.6","42"],dtype=np.string_)

numeric_str.astype(float)

array([ 1.23, -9.6 , 42.  ])

## numpy数组的运算

In [180]:
arr = np.array([[1.,2.,3.]
                ,[4.,5.,6.]
                ])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [181]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [182]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [183]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [184]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [185]:
arr2 = np.array([
    [0.,4.,1.],
    [7.,2.,12.]
])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [186]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

## 索引与切片

In [188]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [189]:
arr[5]

5

In [190]:
arr[1:5]

array([1, 2, 3, 4])

In [191]:
arr[5:8] = -1
arr

array([ 0,  1,  2,  3,  4, -1, -1, -1,  8,  9])

In [192]:
arr_slice = arr[5:8]
arr_slice

array([-1, -1, -1])

In [195]:
arr_slice[1] = 123

arr

array([  0,   1,   2,   3,   4,  64, 123,  64,   8,   9])

In [196]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [197]:
arr2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [198]:
arr2d[0][2]

3

In [199]:
arr2d[0,2]

3

In [200]:
arr3d = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [201]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [202]:
old_values = arr3d[0].copy()
arr3d[0] = 42

In [203]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [205]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [206]:
arr3d[1,0]

array([7, 8, 9])

In [208]:
x=arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [209]:
x[0]

array([7, 8, 9])

## 切片索引

In [210]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [211]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [212]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [219]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [214]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [221]:
lower_dim_slice = arr2d[1, :2]

lower_dim_slice

array([4, 5])

In [222]:
lower_dim_slice.shape

(2,)

In [223]:
arr2d[:2,2]

array([3, 6])

In [225]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [226]:
arr2d[:2,1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## 布尔型索引

In [233]:
names = np.array([
    'bob','joe','will','bob','will','joe','joe'
])
data = np.array([
    [4,7],
    [0,2],
    [-5,6],
    [0,0],
    [1,2],
    [-12,-4],
    [3,4]
])

In [234]:
names

array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'], dtype='<U4')

In [235]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [236]:
names == 'bob'

array([ True, False, False,  True, False, False, False])

In [237]:
data[names=='bob']

array([[4, 7],
       [0, 0]])

In [239]:
data[names=='bob',1:]

array([[7],
       [0]])

In [240]:
names!='bob'

array([False,  True,  True, False,  True,  True,  True])

In [241]:
~(names == 'bob')

array([False,  True,  True, False,  True,  True,  True])

In [242]:
data[~(names=='bob')]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [244]:
mask = (names=='bob') | (names=='will')
mask

array([ True, False,  True,  True,  True, False, False])

In [245]:
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [246]:
data[data<0] = 0
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [247]:
data[names!='joe'] = 7
data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])

## 花式索引

In [248]:
arr = np.zeros(
    (8,4)
)

In [249]:
for i in range(8):
    arr[i] = i

In [250]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [251]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [252]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [254]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [255]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

## 数组转置和轴对换

In [257]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [258]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [259]:
np.dot(arr.T,arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [260]:
np.dot(arr,arr.T)

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [261]:
arr.T @ arr

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [262]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [263]:
arr.swapaxes(0,1)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])